# Generated by Django 4.1.3 on 2024-06-10 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_addcashtowallet_recepient_addcashtowallet_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addcashtowallet',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 10)),
        ),
        migrations.AlterField(
            model_name='givesalary',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 10)),
        ),
        migrations.AlterField(
            model_name='paytocourse',
            name='date',
            field=models.DateField(default=datetime.date(2024, 6, 10)),
        ),
    ]
