# Generated by Django 4.1.3 on 2024-06-11 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_alter_addcashtowallet_date_alter_givesalary_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paytocourse',
            name='cheque_image',
            field=models.ImageField(blank=True, null=True, upload_to='cheques/'),
        ),
        migrations.AddField(
            model_name='paytocourse',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
        migrations.AlterField(
            model_name='paytocourse',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
